name: CircuitPython CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_t-echo:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Install dependence
      run: sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
    - name: Build T-DisplayS3
      run: |
        cp config_T-DisplayS3 config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T-DisplayS3_firmware
        path: ./bin/esp32s3/LILYGO_T-DisplayS3/
